{% set name = "mkdocs-graphviz" %}
{% set version = "1.4.91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_graphviz-{{ version }}.tar.gz
  sha256: 26fd575026a376d1134045fa9e6c161ea36137fe8e370b8ceb10f36cfdf8ca15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=2.3.1
    - python >=3.6

test:
  imports:
    - mkdocs_graphviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/rod2ik/mkdocs-graphviz.git
  summary: Render Graphviz graphs in Mkdocs directly from your Markdown
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rod2ik
    - vallsv
