{% set name = "mkdocs-graphviz" %}
{% set version = "1.4.97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_graphviz-{{ version }}.tar.gz
  sha256: b7814b1f21dc3ee444b62823b0b3b6c17117eab5004519ae10dae7d474597614

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=2.3.1
    - python >=3.6

test:
  imports:
    - mkdocs_graphviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/rod2ik/mkdocs-graphviz.git
  summary: Render Graphviz graphs in Mkdocs directly from your Markdown
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rod2ik
    - vallsv
