{% set name = "mkdocs-graphviz" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_graphviz-{{ version }}.tar.gz
  sha256: 137209e263b06f859ca47127d1ca9a6fad22ba73503e79848e7d68995dff9e1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=2.3.1
    - python >=3.6

test:
  imports:
    - mkdocs_graphviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/rodrigo.schwencke/mkdocs-graphviz.git
  summary: Render Graphviz graphs in Mkdocs directly from your Markdown
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rod2ik
    - vallsv
